# Storytelling with Data! in Altair

by Maisa de Oliveira Fraiz

## Introduction

This project aims to replicate the examples from Cole Nussbaumer's book, "Storytelling with Data - Let's Practice!", using `Python Altair`. Our primary objective is to document the reasoning behind the modifications proposed by the author, while also highlighting the challenges that arise when transitioning from the book's Excel-based approach to programming in a different software environment.

`Altair` was selected for this project due to its declarative syntax, interactivity, grammar of graphics, and compatibility with `Streamlit` and other web formatting tools, while within the user-friendly Python environment. Anticipated challenges include the comparatively smaller documentation and development community of Altair compared to more established libraries like `Matplotlib`, `Seaborn`, or `Plotly`. Furthermore, tasks that might appear straightforward in Excel may require multiple iterations to translate effectively into the language.

## Imports

In [2]:
import pandas as pd
import numpy as np
import altair as alt

## Chapter 2 - Choose an effective visual

*"When I have some data I need to show, how do I do that in an effective way?"*

This chapter's exercises aim to incentivize evaluating different graphs for the same data in order to understand the strengths and constraints of each, helping in the process of finding the best medium to present the information you want to highlight.

#

### Exercise 2.4 - practice in your tool

The data for this exercise can be found here: https://www.storytellingwithdata.com/letspractice/downloads

In [5]:
# Loading considering the NaN caused by Excel formatting
table = pd.read_excel(r"..\..\Data\2.4 EXERCISE.xlsx", usecols = [1, 2, 3], header = 4)
table

       DATE  CAPACITY  DEMAND
0   2019-04     29263   46193
1   2019-05     28037   49131
2   2019-06     21596   50124
3   2019-07     25895   48850
4   2019-08     25813   47602
5   2019-09     22427   43697
6   2019-10     23605   41058
7   2019-11     24263   37364
8   2019-12     24243   34364
9   2020-01     25533   34149
10  2020-02     24467   25573
11  2020-03     25194   25284

In [6]:
# Transforming data into long-format

melted_table = pd.melt(table, id_vars = ['DATE'], var_name = 'Metric', value_name = 'Value')
melted_table

       DATE    Metric  Value
0   2019-04  CAPACITY  29263
1   2019-05  CAPACITY  28037
2   2019-06  CAPACITY  21596
3   2019-07  CAPACITY  25895
4   2019-08  CAPACITY  25813
5   2019-09  CAPACITY  22427
6   2019-10  CAPACITY  23605
7   2019-11  CAPACITY  24263
8   2019-12  CAPACITY  24243
9   2020-01  CAPACITY  25533
10  2020-02  CAPACITY  24467
11  2020-03  CAPACITY  25194
12  2019-04    DEMAND  46193
13  2019-05    DEMAND  49131
14  2019-06    DEMAND  50124
15  2019-07    DEMAND  48850
16  2019-08    DEMAND  47602
17  2019-09    DEMAND  43697
18  2019-10    DEMAND  41058
19  2019-11    DEMAND  37364
20  2019-12    DEMAND  34364
21  2020-01    DEMAND  34149
22  2020-02    DEMAND  25573
23  2020-03    DEMAND  25284

In [13]:
alt.Chart(melted_table).mark_bar().encode(
    y = alt.Y('Value', axis = alt.Axis(grid = False)),
    x = alt.X('Metric'),
    column = 'DATE',
    color = alt.Color('Metric', scale = alt.Scale(range = ['#b4c6e4', '#4871b7']))
    ).configure_view(stroke = None)

alt.Chart(...)